# Generated by Django 4.2.6 on 2023-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_user', '0004_profile_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='premium',
        ),
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
