# Generated by Django 4.2.6 on 2023-10-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_chapter',
            old_name='chapter',
            new_name='chapter_book',
        ),
    ]
