# Generated by Django 4.2.6 on 2023-10-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0006_alter_book_details_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_details',
            old_name='page',
            new_name='page_detail',
        ),
    ]
