# Generated by Django 4.2.6 on 2023-10-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0007_rename_page_book_details_page_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='page_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_book.ebook'),
        ),
    ]
