# Generated by Django 4.2.6 on 2023-10-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0009_alter_book_details_page_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='page_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='e_book.book_chapter'),
        ),
    ]
