# Generated by Django 4.2.6 on 2023-10-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0012_alter_book_details_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='page_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='e_book.book_chapter'),
        ),
    ]
