# Generated by Django 4.2.6 on 2023-10-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0013_alter_book_details_page_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='offer_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
