# Generated by Django 4.2.6 on 2023-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0014_ebook_description_ebook_offer_ebook_offer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
